// SLEEP — Walch et al. 2019 wrist sleep stager (Wake / NREM / REM).
//
// FAITHFUL PORT of the validated 3-class wrist stager from:
//   Walch O, Huang Y, Forger D, Goldstein C. "Sleep stage prediction with raw
//   acceleration and photoplethysmography heart rate data derived from a
//   consumer wearable device." Sleep. 2019;42(12):zsz180.
//   Open code: github.com/ojwalch/sleep_classifiers (MIT).
//   Open data:  PhysioNet sleep-accel v1.0.0.
//
// MODEL: multinomial logistic regression (softmax) over THREE features per
// 30-s epoch — Walch's no-MATLAB default feature set {count, heart_rate,
// cosine} (their `get_base_feature_sets()[3]`). The coefficient matrix in
// [_walchCoef] / [_walchIntercept] was TRAINED OFFLINE on all 31 PhysioNet
// Apple-Watch subjects (25 508 scored 30-s epochs) using the authors' own
// feature pipeline; full provenance + leave-one-subject-out accuracy is in the
// const doc-comment on [_walchCoef] below. The shipped app does NO training —
// it only evaluates these fixed weights.
//
// HONESTY:
//   * Wake / NREM / REM is the VALIDATED Walch output (tier ESTIMATE — a wrist
//     3-class autonomic estimate, never a PSG hypnogram; we never emit
//     N1/N2/N3).
//   * The Light/Deep split inside NREM (STEP 2) is an UNVALIDATED, LOW-
//     CONFIDENCE overlay derived from an HR-depth rule — it is NOT part of
//     Walch and has no PSG validation. Deep is flagged low-confidence.
//
// SUBSTRATE CAVEAT (count feature): Walch derives the motion "activity count"
// from RAW 50 Hz tri-axial accel via a 3–11 Hz band-pass + 15 s binned-max
// aggregation (Apple-Watch ActivityCountService). Our substrate is 1 Hz accel,
// whose 0.5 Hz Nyquist limit makes that exact band-pass IMPOSSIBLE. We
// substitute the standard 1 Hz amplitude index (ENMO, van Hees 2013) as the
// per-second activity-count analog, then apply Walch's EXACT downstream
// windowed Gaussian smoothing. The HR feature and the cosine clock feature are
// ported EXACTLY. This is the one unavoidable fidelity gap, documented here and
// in the metric note.

import 'dart:math' as math;
import '../types.dart';
import '../util.dart';
import 'accounting.dart' show SleepStage;
import 'stager.dart' show StagerResult, consolidateSleepStages;

// ============================================================================
// Trained coefficients — DO NOT hand-edit. Generated by tool/train_walch.py
// from PhysioNet sleep-accel v1.0.0 via the Walch feature pipeline.
// Feature order: [count, heart_rate, cosine].  Classes: [wake, nrem, rem].
// Softmax: P(k) ∝ exp(intercept[k] + Σ_f coef[k][f]·x[f]).
// ============================================================================

/// Trained on PhysioNet sleep-accel v1.0.0 — all 31 Apple-Watch subjects,
/// 25 508 scored 30-s epochs. Multinomial logistic regression, lbfgs,
/// class_weight='balanced', C=1.0. Leave-one-subject-out: accuracy 0.569,
/// Cohen κ 0.272 (a 3-class wrist stager that ACTUALLY separates W/N/R — the
/// unbalanced fit collapses to ~95% NREM, κ ~0.06, so balanced is the honest
/// choice). Features (count, HR) are computed over the IN-BED WINDOW SPAN so
/// the gRef/count scale and HR DoG/percentile match exactly what walchStager
/// sees at inference (no train/serve skew).
/// Feature order: [count, heart_rate, cosine].  Classes: [wake, nrem, rem].
const List<List<double>> _walchCoef = [
  [10.644217, 1.859643, 3.038471], // wake
  [-4.437099, -1.973557, -0.260138], // nrem
  [-6.207119, 0.113914, -2.778333], // rem
];
const List<double> _walchIntercept = [1.403035, 0.719870, -2.122906]; // W,N,R

/// True once real trained weights are embedded (placeholder check).
bool get _coeffsLoaded =>
    _walchIntercept.any((v) => v != 0.0) ||
    _walchCoef.any((row) => row.any((v) => v != 0.0));

// ---------------------------------------------------------------------------
// Walch feature constants (verbatim from sleep_classifiers/source).
// ---------------------------------------------------------------------------

/// Epoch duration (Constants.EPOCH_DURATION_IN_SECONDS = 30).
const int _walchEpochSec = 30;

/// Feature window half-width, seconds. Walch:
///   WINDOW_SIZE = 10 * 30 - 15 = 285   (ActivityCount/HeartRateFeatureService)
/// The feature window for an epoch at time t spans (t-285, t+30+285).
const int _windowSize = 10 * 30 - 15; // 285

/// Result of the Walch stager: the standard [StagerResult] plus a parallel
/// per-epoch Deep-NREM flag (LOW CONFIDENCE — see STEP 2). `deepFlag[i]` is true
/// where epoch i is NREM that the HR-depth rule labels Deep; Light is NREM with
/// the flag false. The flag is meaningless for non-NREM epochs.
class WalchStagerResult {
  final StagerResult base;
  final List<bool> deepFlag; // per-epoch, aligned with base.stages
  const WalchStagerResult(this.base, this.deepFlag);
}

/// Walch et al. 2019 wrist 3-class sleep stager (drop-in for [autonomicStager]).
///
/// [hr1hz]  per-second HR (bpm; 0 = off-skin), within the in-bed window.
/// [accel]  per-second gravity vectors for the SAME window (same length/base).
/// [epochSec] epoch granularity; Walch is validated at 30 s (default).
/// [clockHourAtStart] local clock hour (0..24, fractional ok) of the FIRST
///   sample. Drives the cosine clock feature; when null the feature is built
///   from epoch index only (Walch's `build_cosine` uses elapsed time from the
///   first epoch — i.e. start-hour 0 — which we replicate when null).
///
/// Returns the SAME [StagerResult] shape the pipeline expects (W/NREM/REM
/// stages + epochSec + pcts). Post-processing (Webster rescore +
/// consolidateSleepStages) is applied AFTER inference for a stable hypnogram.
Metric<StagerResult> walchStager(
  List<double> hr1hz,
  List<AccelSample> accel, {
  int epochSec = _walchEpochSec,
  double? clockHourAtStart,
}) {
  return _walchStagerFull(hr1hz, accel,
          epochSec: epochSec, clockHourAtStart: clockHourAtStart)
      .let((r) => r.metric);
}

/// Internal: returns both the [Metric]<StagerResult> and the Deep-flag overlay.
class _WalchOut {
  final Metric<StagerResult> metric;
  final List<bool> deepFlag;
  const _WalchOut(this.metric, this.deepFlag);
}

extension _Let<T> on T {
  R let<R>(R Function(T) f) => f(this);
}

_WalchOut _walchStagerFull(
  List<double> hr1hz,
  List<AccelSample> accel, {
  required int epochSec,
  double? clockHourAtStart,
}) {
  const inputs = ['hr_1hz', 'accel_1hz', 'cosine_clock'];
  final n = math.min(hr1hz.length, accel.length);

  if (!_coeffsLoaded) {
    return _WalchOut(
      const Metric<StagerResult>.absent(
        tier: Tier.estimate,
        inputs_used: inputs,
        note: 'Walch coefficients not yet trained/embedded (placeholder)',
      ),
      const <bool>[],
    );
  }
  if (n < epochSec * 4) {
    return _WalchOut(
      const Metric<StagerResult>.absent(
        tier: Tier.estimate,
        inputs_used: inputs,
        note: 'too short for Walch staging',
      ),
      const <bool>[],
    );
  }
  final nEpoch = n ~/ epochSec;
  if (nEpoch < 3) {
    return _WalchOut(
      const Metric<StagerResult>.absent(
        tier: Tier.estimate,
        inputs_used: inputs,
        note: 'too few epochs for Walch staging',
      ),
      const <bool>[],
    );
  }

  // --- Per-second activity-count analog (substrate substitution, see header).
  // Walch: 50 Hz raw → 3–11 Hz band-pass → |·| → 128-bin digitize → 15 s
  // binned-max → counts=(c-18)*3.07, clipped ≥0. UNREPLICABLE on 1 Hz. We use
  // the per-second ENMO amplitude index (van Hees 2013): ENMO = max(0, ‖a‖ − g).
  // g is auto-calibrated as the median magnitude over the still portion.
  final mag = List<double>.filled(n, 0);
  for (var i = 0; i < n; i++) {
    final a = accel[i];
    mag[i] = math.sqrt(a.x * a.x + a.y * a.y + a.z * a.z);
  }
  final gRef = _calibrateG(mag);
  final count1hz = List<double>.filled(n, 0);
  for (var i = 0; i < n; i++) {
    final e = mag[i] - gRef;
    count1hz[i] = e > 0 ? e : 0.0;
  }

  // --- HR feature pre-processing (Walch HeartRateFeatureService verbatim):
  //   1. 1 Hz interpolate (already 1 Hz; carry last-valid across off-skin 0s).
  //   2. convolve with Difference-of-Gaussians (σ1=120, σ2=600, scalar=0.75)
  //      over the WINDOW_SIZE kernel, after mean-subtraction.
  //   3. normalize by the 90th percentile of |signal|.
  // The per-epoch HR feature is then std(DoG-HR) over the ±285 s window.
  final hrInterp = _interpolateHr(hr1hz, n);
  final hrDog = _convolveWithDog(hrInterp, _windowSize);
  final absHr = [for (final v in hrDog) v.abs()];
  final scalar = percentile(absHr, 90) ?? 1.0;
  final hrNorm = [for (final v in hrDog) scalar != 0 ? v / scalar : v];

  // --- Per-epoch features ----------------------------------------------------
  final fCount = List<double>.filled(nEpoch, 0);
  final fHr = List<double>.filled(nEpoch, 0);
  final fCos = List<double>.filled(nEpoch, 0);
  final epMeanHr = List<double>.filled(nEpoch, double.nan); // for STEP 2
  final epHrSd = List<double>.filled(nEpoch, 0); // for STEP 2

  final startHour = clockHourAtStart ?? 0.0;

  for (var e = 0; e < nEpoch; e++) {
    // Epoch centre time (s from window start), matching Walch's epoch timestamp
    // = first-epoch-start + e*30 ; we treat the window start as t0.
    final epochT = e * epochSec; // seconds since window start

    // Window [epochT-285, epochT+epochSec+285) clipped to [0,n).
    final lo = math.max(0, epochT - _windowSize);
    final hi = math.min(n, epochT + epochSec + _windowSize);

    // COUNT feature: Walch get_feature = smooth_gauss over the window values
    // (Gaussian-weighted single value, σ=50 s, kernel length = window length).
    fCount[e] = _smoothGauss(count1hz, lo, hi);

    // HR feature: std of the DoG-normalized HR over the window.
    fHr[e] = _stdRange(hrNorm, lo, hi);

    // COSINE clock feature (TimeBasedFeatureService.cosine_proxy verbatim):
    //   -cos((t - 5h)*2π / 24h), t in seconds since first epoch.
    // We add the local start-hour so the cosine is phased to wall-clock when
    // clockHourAtStart is supplied (peak sleep-drive ~05:00 local).
    final tAbsSec = (startHour * 3600.0) + epochT;
    fCos[e] = _cosineProxy(tAbsSec);

    // STEP-2 raw HR stats over the epoch (NOT a Walch feature).
    final vals = <double>[];
    final s = e * epochSec;
    for (var i = s; i < math.min(s + epochSec, n); i++) {
      if (hr1hz[i] > 0) vals.add(hr1hz[i]);
    }
    if (vals.isNotEmpty) epMeanHr[e] = mean(vals)!;
    epHrSd[e] = vals.length >= 2 ? (stddev(vals) ?? 0) : 0;
  }

  // --- Multinomial logistic inference (softmax) ------------------------------
  final stages = List<SleepStage>.filled(nEpoch, SleepStage.wake);
  for (var e = 0; e < nEpoch; e++) {
    final x = [fCount[e], fHr[e], fCos[e]];
    final logits = List<double>.filled(3, 0);
    for (var k = 0; k < 3; k++) {
      var z = _walchIntercept[k];
      for (var f = 0; f < 3; f++) {
        z += _walchCoef[k][f] * x[f];
      }
      logits[k] = z;
    }
    // argmax (softmax is monotone, argmax of logits = argmax of probs).
    var best = 0;
    for (var k = 1; k < 3; k++) {
      if (logits[k] > logits[best]) best = k;
    }
    // classes: 0 wake, 1 nrem, 2 rem.
    stages[e] = best == 0
        ? SleepStage.wake
        : (best == 1 ? SleepStage.nrem : SleepStage.rem);
  }

  // --- Post-processing: Webster sleep-continuity rescore (reuse stager.dart's
  //     proven implementation via a private re-impl here to avoid a cycle) then
  //     architecture consolidation (consolidateSleepStages, public & pure).
  _websterRescore(stages, epochSec);
  final sm = consolidateSleepStages(stages, epochSec);

  // --- STEP 2: LOW-CONFIDENCE Light/Deep split within NREM -------------------
  // Rule (UNVALIDATED, ESTIMATE): Deep sleep (N3/SWS) is the parasympathetic
  // floor — HR sits near the night's NREM minimum AND is stable. We label a
  // NREM epoch Deep when BOTH (a) its mean HR is within the lowest band of the
  // night's NREM HR (≤ floor + 0.33·(median−floor), floor = NREM-HR 10th pct)
  // AND (b) its intra-epoch HR SD is at/below the night-median NREM epoch SD.
  // Contiguity is enforced via a 3-min minimum-bout merge so Deep appears as
  // consolidated SWS bouts, not single-epoch flicker. This is an HR-depth
  // heuristic ONLY — NOT Walch, NOT PSG-validated; Deep is flagged LOW
  // CONFIDENCE and must be surfaced as an estimate.
  final nremHr = [
    for (var e = 0; e < nEpoch; e++)
      if (sm[e] == SleepStage.nrem && !epMeanHr[e].isNaN) epMeanHr[e]
  ];
  final deepFlag = List<bool>.filled(nEpoch, false);
  if (nremHr.length >= 4) {
    final floor = percentile(nremHr, 10)!;
    final med = median(nremHr)!;
    final deepHrThresh = floor + 0.33 * (med - floor);
    final nremSd = [
      for (var e = 0; e < nEpoch; e++)
        if (sm[e] == SleepStage.nrem && epHrSd[e] > 0) epHrSd[e]
    ];
    final sdMed = nremSd.isNotEmpty ? median(nremSd)! : double.infinity;
    for (var e = 0; e < nEpoch; e++) {
      if (sm[e] != SleepStage.nrem || epMeanHr[e].isNaN) continue;
      final lowHr = epMeanHr[e] <= deepHrThresh;
      final stable = epHrSd[e] <= sdMed;
      deepFlag[e] = lowHr && stable;
    }
    _mergeShortDeepBouts(deepFlag, sm, epochSec);
  }

  // --- Percentages -----------------------------------------------------------
  var w = 0, nr = 0, r = 0;
  for (final s in sm) {
    switch (s) {
      case SleepStage.wake:
        w++;
        break;
      case SleepStage.nrem:
        nr++;
        break;
      case SleepStage.rem:
        r++;
        break;
    }
  }
  final tot = sm.length.toDouble();
  final metric = Metric<StagerResult>(
    value: StagerResult(
      stages: sm,
      epochSec: epochSec,
      wakePct: 100 * w / tot,
      nremPct: 100 * nr / tot,
      remPct: 100 * r / tot,
    ),
    confidence: 0.5, // honesty-bounded: validated 3-class wrist ESTIMATE
    tier: Tier.estimate,
    inputs_used: inputs,
    note: 'Walch et al. 2019 wrist 3-class stager (wake/NREM/REM), multinomial '
        'logistic on {count,HR,cosine}; count uses 1 Hz ENMO in place of '
        'Walch 50 Hz band-pass counts (Nyquist); never N1/N2/N3, not PSG. '
        'Light/Deep split is a LOW-CONFIDENCE HR-depth overlay (unvalidated).',
  );
  return _WalchOut(metric, deepFlag);
}

/// Public variant that also returns the LOW-CONFIDENCE Deep-NREM overlay.
WalchStagerResult walchStagerWithDeep(
  List<double> hr1hz,
  List<AccelSample> accel, {
  int epochSec = _walchEpochSec,
  double? clockHourAtStart,
}) {
  final out = _walchStagerFull(hr1hz, accel,
      epochSec: epochSec, clockHourAtStart: clockHourAtStart);
  final base = out.metric.value ??
      const StagerResult(
          stages: <SleepStage>[],
          epochSec: _walchEpochSec,
          wakePct: 0,
          nremPct: 0,
          remPct: 0);
  return WalchStagerResult(base, out.deepFlag);
}

// ---------------------------------------------------------------------------
// Feature helpers (faithful ports of sleep_classifiers/source/utils.py).
// ---------------------------------------------------------------------------

/// Auto-calibrate 1 g reference: median magnitude over the low-motion portion.
double _calibrateG(List<double> mag) {
  if (mag.isEmpty) return 1.0;
  // |Δ‖a‖| per sample; still = below the median step.
  final steps = <double>[];
  for (var i = 1; i < mag.length; i++) {
    steps.add((mag[i] - mag[i - 1]).abs());
  }
  final stepMed = steps.isNotEmpty ? (median(steps) ?? 0) : 0;
  final still = <double>[];
  for (var i = 1; i < mag.length; i++) {
    if ((mag[i] - mag[i - 1]).abs() <= stepMed) still.add(mag[i]);
  }
  final g = still.isNotEmpty ? median(still) : median(mag);
  if (g == null || g <= 0 || g.isNaN) return 1.0;
  return g;
}

/// Carry-forward interpolation of HR over off-skin (0) gaps; leading 0s filled
/// with the first valid value, so the series is dense like Walch's np.interp.
List<double> _interpolateHr(List<double> hr, int n) {
  final out = List<double>.filled(n, 0);
  // First valid.
  var firstValid = double.nan;
  for (var i = 0; i < n; i++) {
    if (hr[i] > 0) {
      firstValid = hr[i];
      break;
    }
  }
  if (firstValid.isNaN) return out; // all off-skin
  var last = firstValid;
  for (var i = 0; i < n; i++) {
    if (hr[i] > 0) last = hr[i];
    out[i] = last;
  }
  return out;
}

/// Difference-of-Gaussians convolution, VERBATIM port of utils.convolve_with_dog
/// (σ1=120, σ2=600, scalar=0.75, mean-subtracted, boundary-reflected padding).
/// [boxPts] = WINDOW_SIZE. Returns a series the same length as [y].
List<double> _convolveWithDog(List<double> y, int boxPts) {
  final m = mean(y) ?? 0;
  final yc = [for (final v in y) v - m];

  final box = List<double>.filled(boxPts, 0);
  final mu1 = (boxPts / 2.0).toInt();
  const sigma1 = 120.0;
  final mu2 = (boxPts / 2.0).toInt();
  const sigma2 = 600.0;
  const scalar = 0.75;
  for (var i = 0; i < boxPts; i++) {
    box[i] = math.exp(-0.5 * math.pow((i - mu1) / sigma1, 2)) -
        scalar * math.exp(-0.5 * math.pow((i - mu2) / sigma2, 2));
  }

  // Pad by reflecting boundary: prepend flip(y[0:boxPts/2]), append
  // flip(y[-boxPts/2:]) — matching numpy insert in utils.convolve_with_dog.
  final half = (boxPts / 2).toInt();
  final padded = <double>[];
  for (var i = math.min(half, yc.length) - 1; i >= 0; i--) {
    padded.add(yc[i]); // flip of first `half`
  }
  padded.addAll(yc);
  final tail = <double>[];
  for (var i = yc.length - 1; i >= math.max(0, yc.length - half); i--) {
    tail.add(yc[i]); // flip of last `half`
  }
  padded.addAll(tail);

  // 'valid' convolution: output length = len(padded) - boxPts + 1.
  final outLen = padded.length - boxPts + 1;
  if (outLen <= 0) {
    // Window longer than signal: fall back to a single global value broadcast.
    return List<double>.filled(y.length, 0);
  }
  final conv = List<double>.filled(outLen, 0);
  for (var k = 0; k < outLen; k++) {
    var acc = 0.0;
    for (var j = 0; j < boxPts; j++) {
      acc += padded[k + j] * box[boxPts - 1 - j];
    }
    conv[k] = acc;
  }
  // np.convolve(..., 'valid') on a (len+2*half)-padded signal returns
  // ~len(y)+1 samples; we clip/pad to exactly len(y).
  if (conv.length >= y.length) {
    return conv.sublist(0, y.length);
  }
  final out = List<double>.from(conv);
  while (out.length < y.length) {
    out.add(conv.isNotEmpty ? conv.last : 0.0);
  }
  return out;
}

/// Gaussian-weighted single value over [lo,hi), VERBATIM port of
/// utils.smooth_gauss: kernel length = window length, μ = len/2, σ = 50 s.
double _smoothGauss(List<double> y, int lo, int hi) {
  final len = hi - lo;
  if (len <= 0) return 0;
  final mu = (len / 2.0).toInt();
  const sigma = 50.0;
  var wsum = 0.0;
  final w = List<double>.filled(len, 0);
  for (var i = 0; i < len; i++) {
    w[i] = math.exp(-0.5 * math.pow((i - mu) / sigma, 2));
    wsum += w[i];
  }
  if (wsum == 0) return 0;
  var acc = 0.0;
  for (var i = 0; i < len; i++) {
    acc += (w[i] / wsum) * y[lo + i];
  }
  return acc;
}

/// Population/sample std over [lo,hi) (Walch uses numpy np.std = population).
double _stdRange(List<double> y, int lo, int hi) {
  final len = hi - lo;
  if (len <= 0) return 0;
  var sum = 0.0;
  for (var i = lo; i < hi; i++) {
    sum += y[i];
  }
  final m = sum / len;
  var v = 0.0;
  for (var i = lo; i < hi; i++) {
    final d = y[i] - m;
    v += d * d;
  }
  return math.sqrt(v / len); // np.std default = population (ddof=0)
}

/// Cosine clock proxy, VERBATIM port of TimeBasedFeatureService.cosine_proxy:
///   -cos((t - 5h)·2π / 24h),  t in seconds.
double _cosineProxy(double tSec) {
  const shiftSec = 5 * 3600.0; // sleep_drive_cosine_shift = 5 hours
  const day = 24 * 3600.0;
  return -1 * math.cos((tSec - shiftSec) * 2 * math.pi / day);
}

// ---------------------------------------------------------------------------
// Post-processing: Webster rescore (private copy — keeps walch_stager self-
// contained; identical rules to stager.dart). consolidateSleepStages is reused.
// ---------------------------------------------------------------------------

void _websterRescore(List<SleepStage> sm, int epochSec) {
  bool isSleep(SleepStage s) => s != SleepStage.wake;
  final n = sm.length;
  double minToEp(double m) => m * 60.0 / epochSec;

  var onset = -1, lastSleep = -1;
  for (var i = 0; i < n; i++) {
    if (isSleep(sm[i])) {
      if (onset < 0) onset = i;
      lastSleep = i;
    }
  }
  if (onset < 0) return;

  int sleepRunBefore(int i) {
    var c = 0, k = i - 1;
    while (k >= onset && isSleep(sm[k])) {
      c++;
      k--;
    }
    return c;
  }

  int sleepRunAfter(int i) {
    var c = 0, k = i + 1;
    while (k <= lastSleep && isSleep(sm[k])) {
      c++;
      k++;
    }
    return c;
  }

  final rules = <List<double>>[
    [minToEp(15), minToEp(5)],
    [minToEp(10), minToEp(3)],
    [minToEp(4), minToEp(1)],
  ];

  var i = onset;
  while (i <= lastSleep) {
    if (isSleep(sm[i])) {
      i++;
      continue;
    }
    var j = i;
    while (j <= lastSleep && !isSleep(sm[j])) {
      j++;
    }
    final wakeLen = j - i;
    final before = sleepRunBefore(i);
    final after = sleepRunAfter(j - 1);
    final context = math.max(before, after).toDouble();
    var rescore = false;
    for (final r in rules) {
      if (context >= r[0] && wakeLen <= r[1]) {
        rescore = true;
        break;
      }
    }
    if (rescore) {
      for (var k = i; k < j; k++) {
        sm[k] = SleepStage.nrem;
      }
    }
    i = j;
  }
}

/// Merge Deep bouts shorter than 3 min into Light (false), so Deep reads as
/// consolidated SWS rather than single-epoch flicker. LOW-CONFIDENCE overlay.
void _mergeShortDeepBouts(
    List<bool> deepFlag, List<SleepStage> sm, int epochSec) {
  final minEp = (3 * 60.0 / epochSec).round();
  if (minEp <= 1) return;
  final n = deepFlag.length;
  var i = 0;
  while (i < n) {
    if (!deepFlag[i] || sm[i] != SleepStage.nrem) {
      i++;
      continue;
    }
    var j = i;
    while (j < n && deepFlag[j] && sm[j] == SleepStage.nrem) {
      j++;
    }
    if ((j - i) < minEp) {
      for (var k = i; k < j; k++) {
        deepFlag[k] = false;
      }
    }
    i = j;
  }
}
